### ISSUE TITLE
gpu training

### ISSUE THREAD

**Issue by chikiuso** [aoixcat/ACVAE-VC#2]
Hi , I tried to run the training , my gpu (cuda) seem stay idle, what should I do?

**Comment by ariacat3366** [comment]
Please check the following.
- cuda has been installed correctly. 
- this code do data preprocessing before training, and gpu will not run while doing preprocessing. plz check if preprocessing is done.
- is there enough space in your hard disk.

if you still cannot run the code, please report the details of your situation.
thanks.
